package com.drools.rules.goodbye

import com.drools.demo.model.Customer;
import com.drools.demo.model.Gift;

rule "Family goodbye gift"
    when
        $c : Customer(category == "Family")
    then
        Gift goodbyeGift = new Gift(105, "Family Goodbye Gift", "A family photo album");
        insert(goodbyeGift);
end;

rule "Individual goodbye gift"
    when
        $c : Customer(category == "Individual")
    then
        Gift goodbyeGift = new Gift(106, "Individual Goodbye Gift", "A personalized luggage tag");
        insert(goodbyeGift);
end;

rule "Elite goodbye gift"
    when
        $c : Customer(category == "Elite")
    then
        Gift welcomeGift = new Gift(107, "Elite Goodbye Gift", "A Complementary night in Hotel including a delicacies in the farewell gift");
        insert(welcomeGift);
end;

rule "Royal goodbye gift"
    when
        $c : Customer(category == "Royal")
    then
        Gift welcomeGift = new Gift(108, "Royal Goodbye Gift", "Year of Netflix premium membership");
        insert(welcomeGift);
end;
